### ISSUE TITLE
Centering multi-line text broken in pixi 4.1.1, entire library broken in pixi 4.2.3

### ISSUE THREAD

**Issue by rknDA1337** [tleunen/pixi-multistyle-text#6]
Can't seem to get it to work at all, is it just me?

Edit: Tried updating pixi to the latest and it broke everything :P Seems like fonts changed quite a bit

>Deprecation Warning: determineFontProperties is now deprecated, please use the static calculateFontProperties method, e.g : Text.calculateFontProperties(fontStyle);

>Uncaught TypeError: Text.calculateFontProperties is not a function(…)
>determineFontProperties	@	deprecation.js:682
>MultiStyleText.updateText	@	pixi-multistyle-text.js:217
>...

Changing line 217 to this fixed the 'completely broken' issue at least:
>outputTextData[i][j].fontProperties = PIXI.Text.calculateFontProperties(outputTextData[i][j].style.font);

I'm not github savvy enough to do more than comment right now sorry

**Comment by bluepichu** [comment]
Thanks for the report.  I've been aware of this for a bit and have been working on an update to support 4.2 - it's mostly patched but needs a bit of testing before I'm comfortable pushing it out.  Hopefully I'll be able to do that in the next few days.

**Comment by bluepichu** [comment]
See #8 for the fix.
